
namespace QuanLyKhachHang
{
    partial class UC_KhachHang
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UC_KhachHang));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.bunifuPages1 = new Bunifu.UI.WinForms.BunifuPages();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.grbChinhSuaMon = new System.Windows.Forms.GroupBox();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.dtgvKH = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.btnReload = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHuyKH = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLuuKH = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbSuaTenKH = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txbSuaSDT = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnSuaKH = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbSuaMaKH = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnThemKH = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnXoaKH = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbTimTenKH = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnTimKiem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbTimMaKH = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.bunifuPages1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.grbChinhSuaMon.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dtgvKH)).BeginInit();
            this.groupBox3.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPages1
            // 
            this.bunifuPages1.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.bunifuPages1.AllowTransitions = true;
            this.bunifuPages1.Controls.Add(this.tabPage1);
            this.bunifuPages1.Location = new System.Drawing.Point(3, 17);
            this.bunifuPages1.Multiline = true;
            this.bunifuPages1.Name = "bunifuPages1";
            this.bunifuPages1.Page = this.tabPage1;
            this.bunifuPages1.PageIndex = 0;
            this.bunifuPages1.PageName = "tabPage1";
            this.bunifuPages1.PageTitle = "tabPage1";
            this.bunifuPages1.SelectedIndex = 0;
            this.bunifuPages1.Size = new System.Drawing.Size(1148, 598);
            this.bunifuPages1.TabIndex = 0;
            animation1.AnimateOnlyDifferences = false;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.bunifuPages1.Transition = animation1;
            this.bunifuPages1.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.btnReload);
            this.tabPage1.Controls.Add(this.grbChinhSuaMon);
            this.tabPage1.Controls.Add(this.dtgvKH);
            this.tabPage1.Controls.Add(this.groupBox3);
            this.tabPage1.Location = new System.Drawing.Point(4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(1140, 572);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "tabPage1";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // grbChinhSuaMon
            // 
            this.grbChinhSuaMon.Controls.Add(this.btnHuyKH);
            this.grbChinhSuaMon.Controls.Add(this.btnLuuKH);
            this.grbChinhSuaMon.Controls.Add(this.txbSuaTenKH);
            this.grbChinhSuaMon.Controls.Add(this.txbSuaSDT);
            this.grbChinhSuaMon.Controls.Add(this.btnSuaKH);
            this.grbChinhSuaMon.Controls.Add(this.txbSuaMaKH);
            this.grbChinhSuaMon.Controls.Add(this.label10);
            this.grbChinhSuaMon.Controls.Add(this.label11);
            this.grbChinhSuaMon.Controls.Add(this.btnThemKH);
            this.grbChinhSuaMon.Controls.Add(this.label9);
            this.grbChinhSuaMon.Controls.Add(this.btnXoaKH);
            this.grbChinhSuaMon.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grbChinhSuaMon.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.grbChinhSuaMon.Location = new System.Drawing.Point(699, 6);
            this.grbChinhSuaMon.Name = "grbChinhSuaMon";
            this.grbChinhSuaMon.Size = new System.Drawing.Size(423, 557);
            this.grbChinhSuaMon.TabIndex = 46;
            this.grbChinhSuaMon.TabStop = false;
            this.grbChinhSuaMon.Text = "Chỉnh sửa";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label10.Location = new System.Drawing.Point(6, 151);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(137, 20);
            this.label10.TabIndex = 20;
            this.label10.Text = "Tên khách hàng";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label11.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label11.Location = new System.Drawing.Point(9, 229);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(44, 20);
            this.label11.TabIndex = 21;
            this.label11.Text = "SĐT";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label9.Location = new System.Drawing.Point(11, 75);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(131, 20);
            this.label9.TabIndex = 21;
            this.label9.Text = "Mã khách hàng";
            // 
            // dtgvKH
            // 
            this.dtgvKH.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dtgvKH.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtgvKH.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtgvKH.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtgvKH.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtgvKH.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtgvKH.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtgvKH.ColumnHeadersHeight = 40;
            this.dtgvKH.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtgvKH.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvKH.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvKH.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvKH.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtgvKH.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtgvKH.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvKH.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dtgvKH.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtgvKH.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtgvKH.CurrentTheme.Name = null;
            this.dtgvKH.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtgvKH.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvKH.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvKH.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvKH.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtgvKH.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtgvKH.EnableHeadersVisualStyles = false;
            this.dtgvKH.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvKH.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dtgvKH.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtgvKH.HeaderForeColor = System.Drawing.Color.White;
            this.dtgvKH.Location = new System.Drawing.Point(0, 138);
            this.dtgvKH.Name = "dtgvKH";
            this.dtgvKH.RowHeadersVisible = false;
            this.dtgvKH.RowHeadersWidth = 51;
            this.dtgvKH.RowTemplate.Height = 40;
            this.dtgvKH.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtgvKH.Size = new System.Drawing.Size(670, 372);
            this.dtgvKH.TabIndex = 45;
            this.dtgvKH.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dtgvKH.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtgvKH_CellClick_1);
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.txbTimTenKH);
            this.groupBox3.Controls.Add(this.label1);
            this.groupBox3.Controls.Add(this.btnTimKiem);
            this.groupBox3.Controls.Add(this.txbTimMaKH);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.groupBox3.Location = new System.Drawing.Point(6, 6);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(667, 128);
            this.groupBox3.TabIndex = 37;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Tìm kiếm";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label1.Location = new System.Drawing.Point(6, 91);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(131, 20);
            this.label1.TabIndex = 26;
            this.label1.Text = "Mã khách hàng";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label7.Location = new System.Drawing.Point(6, 42);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(131, 20);
            this.label7.TabIndex = 20;
            this.label7.Text = "Mã khách hàng";
            // 
            // btnReload
            // 
            this.btnReload.AllowToggling = false;
            this.btnReload.AnimationSpeed = 200;
            this.btnReload.AutoGenerateColors = true;
            this.btnReload.BackColor = System.Drawing.Color.Transparent;
            this.btnReload.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.btnReload.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReload.BackgroundImage")));
            this.btnReload.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReload.ButtonText = "Reload";
            this.btnReload.ButtonTextMarginLeft = 0;
            this.btnReload.ColorContrastOnClick = 45;
            this.btnReload.ColorContrastOnHover = 45;
            this.btnReload.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnReload.CustomizableEdges = borderEdges1;
            this.btnReload.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReload.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReload.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReload.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReload.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnReload.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnReload.ForeColor = System.Drawing.Color.White;
            this.btnReload.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnReload.IconMarginLeft = 11;
            this.btnReload.IconPadding = 10;
            this.btnReload.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnReload.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.btnReload.IdleBorderRadius = 5;
            this.btnReload.IdleBorderThickness = 1;
            this.btnReload.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.btnReload.IdleIconLeftImage = global::QuanLyKhachHang.Properties.Resources.icons8_database_backup_48;
            this.btnReload.IdleIconRightImage = null;
            this.btnReload.IndicateFocus = false;
            this.btnReload.Location = new System.Drawing.Point(555, 516);
            this.btnReload.Name = "btnReload";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(211)))), ((int)(((byte)(175)))));
            stateProperties1.BorderRadius = 5;
            stateProperties1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties1.BorderThickness = 1;
            stateProperties1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(211)))), ((int)(((byte)(175)))));
            stateProperties1.ForeColor = System.Drawing.Color.White;
            stateProperties1.IconLeftImage = null;
            stateProperties1.IconRightImage = null;
            this.btnReload.onHoverState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(96)))), ((int)(((byte)(61)))));
            stateProperties2.BorderRadius = 5;
            stateProperties2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties2.BorderThickness = 1;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(96)))), ((int)(((byte)(61)))));
            stateProperties2.ForeColor = System.Drawing.Color.White;
            stateProperties2.IconLeftImage = null;
            stateProperties2.IconRightImage = null;
            this.btnReload.OnPressedState = stateProperties2;
            this.btnReload.Size = new System.Drawing.Size(118, 45);
            this.btnReload.TabIndex = 47;
            this.btnReload.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnReload.TextMarginLeft = 0;
            this.btnReload.UseDefaultRadiusAndThickness = true;
            this.btnReload.Click += new System.EventHandler(this.btnReload_Click_1);
            // 
            // btnHuyKH
            // 
            this.btnHuyKH.AllowToggling = false;
            this.btnHuyKH.AnimationSpeed = 200;
            this.btnHuyKH.AutoGenerateColors = true;
            this.btnHuyKH.BackColor = System.Drawing.Color.Transparent;
            this.btnHuyKH.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.btnHuyKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHuyKH.BackgroundImage")));
            this.btnHuyKH.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuyKH.ButtonText = "Huỷ";
            this.btnHuyKH.ButtonTextMarginLeft = 0;
            this.btnHuyKH.ColorContrastOnClick = 45;
            this.btnHuyKH.ColorContrastOnHover = 45;
            this.btnHuyKH.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnHuyKH.CustomizableEdges = borderEdges2;
            this.btnHuyKH.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHuyKH.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHuyKH.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHuyKH.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHuyKH.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHuyKH.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHuyKH.ForeColor = System.Drawing.Color.White;
            this.btnHuyKH.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHuyKH.IconMarginLeft = 11;
            this.btnHuyKH.IconPadding = 10;
            this.btnHuyKH.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHuyKH.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.btnHuyKH.IdleBorderRadius = 5;
            this.btnHuyKH.IdleBorderThickness = 1;
            this.btnHuyKH.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.btnHuyKH.IdleIconLeftImage = null;
            this.btnHuyKH.IdleIconRightImage = null;
            this.btnHuyKH.IndicateFocus = false;
            this.btnHuyKH.Location = new System.Drawing.Point(217, 396);
            this.btnHuyKH.Name = "btnHuyKH";
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(134)))), ((int)(((byte)(147)))));
            stateProperties3.BorderRadius = 5;
            stateProperties3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties3.BorderThickness = 1;
            stateProperties3.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(134)))), ((int)(((byte)(147)))));
            stateProperties3.ForeColor = System.Drawing.Color.White;
            stateProperties3.IconLeftImage = null;
            stateProperties3.IconRightImage = null;
            this.btnHuyKH.onHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(19)))), ((int)(((byte)(33)))));
            stateProperties4.BorderRadius = 5;
            stateProperties4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties4.BorderThickness = 1;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(19)))), ((int)(((byte)(33)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.IconLeftImage = null;
            stateProperties4.IconRightImage = null;
            this.btnHuyKH.OnPressedState = stateProperties4;
            this.btnHuyKH.Size = new System.Drawing.Size(118, 45);
            this.btnHuyKH.TabIndex = 26;
            this.btnHuyKH.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHuyKH.TextMarginLeft = 0;
            this.btnHuyKH.UseDefaultRadiusAndThickness = true;
            this.btnHuyKH.Click += new System.EventHandler(this.btnHuyKH_Click_1);
            // 
            // btnLuuKH
            // 
            this.btnLuuKH.AllowToggling = false;
            this.btnLuuKH.AnimationSpeed = 200;
            this.btnLuuKH.AutoGenerateColors = true;
            this.btnLuuKH.BackColor = System.Drawing.Color.Transparent;
            this.btnLuuKH.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.btnLuuKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLuuKH.BackgroundImage")));
            this.btnLuuKH.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuuKH.ButtonText = "Lưu";
            this.btnLuuKH.ButtonTextMarginLeft = 0;
            this.btnLuuKH.ColorContrastOnClick = 45;
            this.btnLuuKH.ColorContrastOnHover = 45;
            this.btnLuuKH.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnLuuKH.CustomizableEdges = borderEdges3;
            this.btnLuuKH.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLuuKH.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLuuKH.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLuuKH.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLuuKH.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLuuKH.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLuuKH.ForeColor = System.Drawing.Color.White;
            this.btnLuuKH.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLuuKH.IconMarginLeft = 11;
            this.btnLuuKH.IconPadding = 10;
            this.btnLuuKH.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLuuKH.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.btnLuuKH.IdleBorderRadius = 5;
            this.btnLuuKH.IdleBorderThickness = 1;
            this.btnLuuKH.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.btnLuuKH.IdleIconLeftImage = null;
            this.btnLuuKH.IdleIconRightImage = null;
            this.btnLuuKH.IndicateFocus = false;
            this.btnLuuKH.Location = new System.Drawing.Point(72, 396);
            this.btnLuuKH.Name = "btnLuuKH";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(152)))), ((int)(((byte)(181)))));
            stateProperties5.BorderRadius = 5;
            stateProperties5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties5.BorderThickness = 1;
            stateProperties5.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(152)))), ((int)(((byte)(181)))));
            stateProperties5.ForeColor = System.Drawing.Color.White;
            stateProperties5.IconLeftImage = null;
            stateProperties5.IconRightImage = null;
            this.btnLuuKH.onHoverState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(37)))), ((int)(((byte)(67)))));
            stateProperties6.BorderRadius = 5;
            stateProperties6.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties6.BorderThickness = 1;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(37)))), ((int)(((byte)(67)))));
            stateProperties6.ForeColor = System.Drawing.Color.White;
            stateProperties6.IconLeftImage = null;
            stateProperties6.IconRightImage = null;
            this.btnLuuKH.OnPressedState = stateProperties6;
            this.btnLuuKH.Size = new System.Drawing.Size(118, 45);
            this.btnLuuKH.TabIndex = 27;
            this.btnLuuKH.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLuuKH.TextMarginLeft = 0;
            this.btnLuuKH.UseDefaultRadiusAndThickness = true;
            this.btnLuuKH.Click += new System.EventHandler(this.btnLuuKH_Click_1);
            // 
            // txbSuaTenKH
            // 
            this.txbSuaTenKH.AcceptsReturn = false;
            this.txbSuaTenKH.AcceptsTab = false;
            this.txbSuaTenKH.AnimationSpeed = 200;
            this.txbSuaTenKH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbSuaTenKH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbSuaTenKH.BackColor = System.Drawing.Color.Transparent;
            this.txbSuaTenKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbSuaTenKH.BackgroundImage")));
            this.txbSuaTenKH.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.txbSuaTenKH.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbSuaTenKH.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.txbSuaTenKH.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbSuaTenKH.BorderRadius = 1;
            this.txbSuaTenKH.BorderThickness = 1;
            this.txbSuaTenKH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbSuaTenKH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSuaTenKH.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.txbSuaTenKH.DefaultText = "";
            this.txbSuaTenKH.FillColor = System.Drawing.Color.White;
            this.txbSuaTenKH.HideSelection = true;
            this.txbSuaTenKH.IconLeft = null;
            this.txbSuaTenKH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSuaTenKH.IconPadding = 10;
            this.txbSuaTenKH.IconRight = null;
            this.txbSuaTenKH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSuaTenKH.Lines = new string[0];
            this.txbSuaTenKH.Location = new System.Drawing.Point(152, 141);
            this.txbSuaTenKH.MaxLength = 32767;
            this.txbSuaTenKH.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbSuaTenKH.Modified = false;
            this.txbSuaTenKH.Multiline = false;
            this.txbSuaTenKH.Name = "txbSuaTenKH";
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSuaTenKH.OnActiveState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Empty;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSuaTenKH.OnDisabledState = stateProperties8;
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSuaTenKH.OnHoverState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Silver;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSuaTenKH.OnIdleState = stateProperties10;
            this.txbSuaTenKH.PasswordChar = '\0';
            this.txbSuaTenKH.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSuaTenKH.PlaceholderText = "";
            this.txbSuaTenKH.ReadOnly = false;
            this.txbSuaTenKH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbSuaTenKH.SelectedText = "";
            this.txbSuaTenKH.SelectionLength = 0;
            this.txbSuaTenKH.SelectionStart = 0;
            this.txbSuaTenKH.ShortcutsEnabled = true;
            this.txbSuaTenKH.Size = new System.Drawing.Size(253, 35);
            this.txbSuaTenKH.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbSuaTenKH.TabIndex = 23;
            this.txbSuaTenKH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbSuaTenKH.TextMarginBottom = 0;
            this.txbSuaTenKH.TextMarginLeft = 5;
            this.txbSuaTenKH.TextMarginTop = 0;
            this.txbSuaTenKH.TextPlaceholder = "";
            this.txbSuaTenKH.UseSystemPasswordChar = false;
            this.txbSuaTenKH.WordWrap = true;
            // 
            // txbSuaSDT
            // 
            this.txbSuaSDT.AcceptsReturn = false;
            this.txbSuaSDT.AcceptsTab = false;
            this.txbSuaSDT.AnimationSpeed = 200;
            this.txbSuaSDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbSuaSDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbSuaSDT.BackColor = System.Drawing.Color.Transparent;
            this.txbSuaSDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbSuaSDT.BackgroundImage")));
            this.txbSuaSDT.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.txbSuaSDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbSuaSDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.txbSuaSDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbSuaSDT.BorderRadius = 1;
            this.txbSuaSDT.BorderThickness = 1;
            this.txbSuaSDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbSuaSDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSuaSDT.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.txbSuaSDT.DefaultText = "";
            this.txbSuaSDT.FillColor = System.Drawing.Color.White;
            this.txbSuaSDT.HideSelection = true;
            this.txbSuaSDT.IconLeft = null;
            this.txbSuaSDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSuaSDT.IconPadding = 10;
            this.txbSuaSDT.IconRight = null;
            this.txbSuaSDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSuaSDT.Lines = new string[0];
            this.txbSuaSDT.Location = new System.Drawing.Point(152, 219);
            this.txbSuaSDT.MaxLength = 32767;
            this.txbSuaSDT.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbSuaSDT.Modified = false;
            this.txbSuaSDT.Multiline = false;
            this.txbSuaSDT.Name = "txbSuaSDT";
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSuaSDT.OnActiveState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Empty;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSuaSDT.OnDisabledState = stateProperties12;
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSuaSDT.OnHoverState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Silver;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSuaSDT.OnIdleState = stateProperties14;
            this.txbSuaSDT.PasswordChar = '\0';
            this.txbSuaSDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSuaSDT.PlaceholderText = "";
            this.txbSuaSDT.ReadOnly = false;
            this.txbSuaSDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbSuaSDT.SelectedText = "";
            this.txbSuaSDT.SelectionLength = 0;
            this.txbSuaSDT.SelectionStart = 0;
            this.txbSuaSDT.ShortcutsEnabled = true;
            this.txbSuaSDT.Size = new System.Drawing.Size(253, 35);
            this.txbSuaSDT.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbSuaSDT.TabIndex = 22;
            this.txbSuaSDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbSuaSDT.TextMarginBottom = 0;
            this.txbSuaSDT.TextMarginLeft = 5;
            this.txbSuaSDT.TextMarginTop = 0;
            this.txbSuaSDT.TextPlaceholder = "";
            this.txbSuaSDT.UseSystemPasswordChar = false;
            this.txbSuaSDT.WordWrap = true;
            // 
            // btnSuaKH
            // 
            this.btnSuaKH.AllowToggling = false;
            this.btnSuaKH.AnimationSpeed = 200;
            this.btnSuaKH.AutoGenerateColors = true;
            this.btnSuaKH.BackColor = System.Drawing.Color.Transparent;
            this.btnSuaKH.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSuaKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSuaKH.BackgroundImage")));
            this.btnSuaKH.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSuaKH.ButtonText = "Sửa";
            this.btnSuaKH.ButtonTextMarginLeft = 0;
            this.btnSuaKH.ColorContrastOnClick = 45;
            this.btnSuaKH.ColorContrastOnHover = 45;
            this.btnSuaKH.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnSuaKH.CustomizableEdges = borderEdges4;
            this.btnSuaKH.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSuaKH.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSuaKH.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuaKH.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuaKH.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSuaKH.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSuaKH.ForeColor = System.Drawing.Color.White;
            this.btnSuaKH.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSuaKH.IconMarginLeft = 11;
            this.btnSuaKH.IconPadding = 10;
            this.btnSuaKH.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSuaKH.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSuaKH.IdleBorderRadius = 5;
            this.btnSuaKH.IdleBorderThickness = 1;
            this.btnSuaKH.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSuaKH.IdleIconLeftImage = null;
            this.btnSuaKH.IdleIconRightImage = null;
            this.btnSuaKH.IndicateFocus = false;
            this.btnSuaKH.Location = new System.Drawing.Point(152, 318);
            this.btnSuaKH.Name = "btnSuaKH";
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(185)))), ((int)(((byte)(114)))));
            stateProperties15.BorderRadius = 5;
            stateProperties15.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties15.BorderThickness = 1;
            stateProperties15.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(185)))), ((int)(((byte)(114)))));
            stateProperties15.ForeColor = System.Drawing.Color.White;
            stateProperties15.IconLeftImage = null;
            stateProperties15.IconRightImage = null;
            this.btnSuaKH.onHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(70)))), ((int)(((byte)(0)))));
            stateProperties16.BorderRadius = 5;
            stateProperties16.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties16.BorderThickness = 1;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(70)))), ((int)(((byte)(0)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.IconLeftImage = null;
            stateProperties16.IconRightImage = null;
            this.btnSuaKH.OnPressedState = stateProperties16;
            this.btnSuaKH.Size = new System.Drawing.Size(118, 45);
            this.btnSuaKH.TabIndex = 23;
            this.btnSuaKH.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSuaKH.TextMarginLeft = 0;
            this.btnSuaKH.UseDefaultRadiusAndThickness = true;
            this.btnSuaKH.Click += new System.EventHandler(this.btnSuaKH_Click_1);
            // 
            // txbSuaMaKH
            // 
            this.txbSuaMaKH.AcceptsReturn = false;
            this.txbSuaMaKH.AcceptsTab = false;
            this.txbSuaMaKH.AnimationSpeed = 200;
            this.txbSuaMaKH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbSuaMaKH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbSuaMaKH.BackColor = System.Drawing.Color.Transparent;
            this.txbSuaMaKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbSuaMaKH.BackgroundImage")));
            this.txbSuaMaKH.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.txbSuaMaKH.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbSuaMaKH.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.txbSuaMaKH.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbSuaMaKH.BorderRadius = 1;
            this.txbSuaMaKH.BorderThickness = 1;
            this.txbSuaMaKH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbSuaMaKH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSuaMaKH.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.txbSuaMaKH.DefaultText = "";
            this.txbSuaMaKH.Enabled = false;
            this.txbSuaMaKH.FillColor = System.Drawing.Color.White;
            this.txbSuaMaKH.HideSelection = true;
            this.txbSuaMaKH.IconLeft = null;
            this.txbSuaMaKH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSuaMaKH.IconPadding = 10;
            this.txbSuaMaKH.IconRight = null;
            this.txbSuaMaKH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSuaMaKH.Lines = new string[0];
            this.txbSuaMaKH.Location = new System.Drawing.Point(152, 75);
            this.txbSuaMaKH.MaxLength = 32767;
            this.txbSuaMaKH.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbSuaMaKH.Modified = false;
            this.txbSuaMaKH.Multiline = false;
            this.txbSuaMaKH.Name = "txbSuaMaKH";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSuaMaKH.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSuaMaKH.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSuaMaKH.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSuaMaKH.OnIdleState = stateProperties20;
            this.txbSuaMaKH.PasswordChar = '\0';
            this.txbSuaMaKH.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSuaMaKH.PlaceholderText = "";
            this.txbSuaMaKH.ReadOnly = false;
            this.txbSuaMaKH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbSuaMaKH.SelectedText = "";
            this.txbSuaMaKH.SelectionLength = 0;
            this.txbSuaMaKH.SelectionStart = 0;
            this.txbSuaMaKH.ShortcutsEnabled = true;
            this.txbSuaMaKH.Size = new System.Drawing.Size(253, 35);
            this.txbSuaMaKH.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbSuaMaKH.TabIndex = 22;
            this.txbSuaMaKH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbSuaMaKH.TextMarginBottom = 0;
            this.txbSuaMaKH.TextMarginLeft = 5;
            this.txbSuaMaKH.TextMarginTop = 0;
            this.txbSuaMaKH.TextPlaceholder = "";
            this.txbSuaMaKH.UseSystemPasswordChar = false;
            this.txbSuaMaKH.WordWrap = true;
            // 
            // btnThemKH
            // 
            this.btnThemKH.AllowToggling = false;
            this.btnThemKH.AnimationSpeed = 200;
            this.btnThemKH.AutoGenerateColors = true;
            this.btnThemKH.BackColor = System.Drawing.Color.Transparent;
            this.btnThemKH.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnThemKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThemKH.BackgroundImage")));
            this.btnThemKH.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemKH.ButtonText = "Thêm";
            this.btnThemKH.ButtonTextMarginLeft = 0;
            this.btnThemKH.ColorContrastOnClick = 45;
            this.btnThemKH.ColorContrastOnHover = 45;
            this.btnThemKH.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnThemKH.CustomizableEdges = borderEdges5;
            this.btnThemKH.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThemKH.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThemKH.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThemKH.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThemKH.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThemKH.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnThemKH.ForeColor = System.Drawing.Color.White;
            this.btnThemKH.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThemKH.IconMarginLeft = 11;
            this.btnThemKH.IconPadding = 10;
            this.btnThemKH.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThemKH.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnThemKH.IdleBorderRadius = 5;
            this.btnThemKH.IdleBorderThickness = 1;
            this.btnThemKH.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnThemKH.IdleIconLeftImage = null;
            this.btnThemKH.IdleIconRightImage = null;
            this.btnThemKH.IndicateFocus = false;
            this.btnThemKH.Location = new System.Drawing.Point(14, 318);
            this.btnThemKH.Name = "btnThemKH";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties21.BorderRadius = 5;
            stateProperties21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties21.BorderThickness = 1;
            stateProperties21.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties21.ForeColor = System.Drawing.Color.White;
            stateProperties21.IconLeftImage = null;
            stateProperties21.IconRightImage = null;
            this.btnThemKH.onHoverState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties22.BorderRadius = 5;
            stateProperties22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties22.BorderThickness = 1;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties22.ForeColor = System.Drawing.Color.White;
            stateProperties22.IconLeftImage = null;
            stateProperties22.IconRightImage = null;
            this.btnThemKH.OnPressedState = stateProperties22;
            this.btnThemKH.Size = new System.Drawing.Size(118, 45);
            this.btnThemKH.TabIndex = 24;
            this.btnThemKH.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThemKH.TextMarginLeft = 0;
            this.btnThemKH.UseDefaultRadiusAndThickness = true;
            this.btnThemKH.Click += new System.EventHandler(this.btnThemKH_Click_1);
            // 
            // btnXoaKH
            // 
            this.btnXoaKH.AllowToggling = false;
            this.btnXoaKH.AnimationSpeed = 200;
            this.btnXoaKH.AutoGenerateColors = true;
            this.btnXoaKH.BackColor = System.Drawing.Color.Transparent;
            this.btnXoaKH.BackColor1 = System.Drawing.Color.Red;
            this.btnXoaKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoaKH.BackgroundImage")));
            this.btnXoaKH.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaKH.ButtonText = "Xoá";
            this.btnXoaKH.ButtonTextMarginLeft = 0;
            this.btnXoaKH.ColorContrastOnClick = 45;
            this.btnXoaKH.ColorContrastOnHover = 45;
            this.btnXoaKH.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnXoaKH.CustomizableEdges = borderEdges6;
            this.btnXoaKH.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoaKH.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnXoaKH.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoaKH.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoaKH.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoaKH.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnXoaKH.ForeColor = System.Drawing.Color.White;
            this.btnXoaKH.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXoaKH.IconMarginLeft = 11;
            this.btnXoaKH.IconPadding = 10;
            this.btnXoaKH.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXoaKH.IdleBorderColor = System.Drawing.Color.Red;
            this.btnXoaKH.IdleBorderRadius = 5;
            this.btnXoaKH.IdleBorderThickness = 1;
            this.btnXoaKH.IdleFillColor = System.Drawing.Color.Red;
            this.btnXoaKH.IdleIconLeftImage = null;
            this.btnXoaKH.IdleIconRightImage = null;
            this.btnXoaKH.IndicateFocus = false;
            this.btnXoaKH.Location = new System.Drawing.Point(287, 318);
            this.btnXoaKH.Name = "btnXoaKH";
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            stateProperties23.BorderRadius = 5;
            stateProperties23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties23.BorderThickness = 1;
            stateProperties23.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            stateProperties23.ForeColor = System.Drawing.Color.White;
            stateProperties23.IconLeftImage = null;
            stateProperties23.IconRightImage = null;
            this.btnXoaKH.onHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            stateProperties24.BorderRadius = 5;
            stateProperties24.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties24.BorderThickness = 1;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.IconLeftImage = null;
            stateProperties24.IconRightImage = null;
            this.btnXoaKH.OnPressedState = stateProperties24;
            this.btnXoaKH.Size = new System.Drawing.Size(118, 45);
            this.btnXoaKH.TabIndex = 22;
            this.btnXoaKH.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoaKH.TextMarginLeft = 0;
            this.btnXoaKH.UseDefaultRadiusAndThickness = true;
            this.btnXoaKH.Click += new System.EventHandler(this.btnXoaKH_Click_1);
            // 
            // txbTimTenKH
            // 
            this.txbTimTenKH.AcceptsReturn = false;
            this.txbTimTenKH.AcceptsTab = false;
            this.txbTimTenKH.AnimationSpeed = 200;
            this.txbTimTenKH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbTimTenKH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbTimTenKH.BackColor = System.Drawing.Color.Transparent;
            this.txbTimTenKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbTimTenKH.BackgroundImage")));
            this.txbTimTenKH.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.txbTimTenKH.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbTimTenKH.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.txbTimTenKH.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbTimTenKH.BorderRadius = 1;
            this.txbTimTenKH.BorderThickness = 1;
            this.txbTimTenKH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbTimTenKH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTimTenKH.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.txbTimTenKH.DefaultText = "";
            this.txbTimTenKH.FillColor = System.Drawing.Color.White;
            this.txbTimTenKH.HideSelection = true;
            this.txbTimTenKH.IconLeft = null;
            this.txbTimTenKH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTimTenKH.IconPadding = 10;
            this.txbTimTenKH.IconRight = null;
            this.txbTimTenKH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTimTenKH.Lines = new string[0];
            this.txbTimTenKH.Location = new System.Drawing.Point(172, 81);
            this.txbTimTenKH.MaxLength = 32767;
            this.txbTimTenKH.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbTimTenKH.Modified = false;
            this.txbTimTenKH.Multiline = false;
            this.txbTimTenKH.Name = "txbTimTenKH";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTimTenKH.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbTimTenKH.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTimTenKH.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTimTenKH.OnIdleState = stateProperties28;
            this.txbTimTenKH.PasswordChar = '\0';
            this.txbTimTenKH.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbTimTenKH.PlaceholderText = "";
            this.txbTimTenKH.ReadOnly = false;
            this.txbTimTenKH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbTimTenKH.SelectedText = "";
            this.txbTimTenKH.SelectionLength = 0;
            this.txbTimTenKH.SelectionStart = 0;
            this.txbTimTenKH.ShortcutsEnabled = true;
            this.txbTimTenKH.Size = new System.Drawing.Size(253, 35);
            this.txbTimTenKH.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbTimTenKH.TabIndex = 27;
            this.txbTimTenKH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbTimTenKH.TextMarginBottom = 0;
            this.txbTimTenKH.TextMarginLeft = 5;
            this.txbTimTenKH.TextMarginTop = 0;
            this.txbTimTenKH.TextPlaceholder = "";
            this.txbTimTenKH.UseSystemPasswordChar = false;
            this.txbTimTenKH.WordWrap = true;
            // 
            // btnTimKiem
            // 
            this.btnTimKiem.AllowToggling = false;
            this.btnTimKiem.AnimationSpeed = 200;
            this.btnTimKiem.AutoGenerateColors = true;
            this.btnTimKiem.BackColor = System.Drawing.Color.Transparent;
            this.btnTimKiem.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.btnTimKiem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTimKiem.BackgroundImage")));
            this.btnTimKiem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTimKiem.ButtonText = "Tìm kiếm";
            this.btnTimKiem.ButtonTextMarginLeft = 0;
            this.btnTimKiem.ColorContrastOnClick = 45;
            this.btnTimKiem.ColorContrastOnHover = 45;
            this.btnTimKiem.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnTimKiem.CustomizableEdges = borderEdges7;
            this.btnTimKiem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTimKiem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTimKiem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTimKiem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTimKiem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTimKiem.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTimKiem.ForeColor = System.Drawing.Color.White;
            this.btnTimKiem.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTimKiem.IconMarginLeft = 11;
            this.btnTimKiem.IconPadding = 10;
            this.btnTimKiem.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTimKiem.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.btnTimKiem.IdleBorderRadius = 5;
            this.btnTimKiem.IdleBorderThickness = 1;
            this.btnTimKiem.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.btnTimKiem.IdleIconLeftImage = global::QuanLyKhachHang.Properties.Resources.icons8_search_client_48;
            this.btnTimKiem.IdleIconRightImage = null;
            this.btnTimKiem.IndicateFocus = false;
            this.btnTimKiem.Location = new System.Drawing.Point(500, 55);
            this.btnTimKiem.Name = "btnTimKiem";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(211)))), ((int)(((byte)(175)))));
            stateProperties29.BorderRadius = 5;
            stateProperties29.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties29.BorderThickness = 1;
            stateProperties29.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(211)))), ((int)(((byte)(175)))));
            stateProperties29.ForeColor = System.Drawing.Color.White;
            stateProperties29.IconLeftImage = null;
            stateProperties29.IconRightImage = null;
            this.btnTimKiem.onHoverState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(96)))), ((int)(((byte)(61)))));
            stateProperties30.BorderRadius = 5;
            stateProperties30.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties30.BorderThickness = 1;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(96)))), ((int)(((byte)(61)))));
            stateProperties30.ForeColor = System.Drawing.Color.White;
            stateProperties30.IconLeftImage = null;
            stateProperties30.IconRightImage = null;
            this.btnTimKiem.OnPressedState = stateProperties30;
            this.btnTimKiem.Size = new System.Drawing.Size(118, 45);
            this.btnTimKiem.TabIndex = 25;
            this.btnTimKiem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTimKiem.TextMarginLeft = 0;
            this.btnTimKiem.UseDefaultRadiusAndThickness = true;
            this.btnTimKiem.Click += new System.EventHandler(this.btnTimKiem_Click);
            // 
            // txbTimMaKH
            // 
            this.txbTimMaKH.AcceptsReturn = false;
            this.txbTimMaKH.AcceptsTab = false;
            this.txbTimMaKH.AnimationSpeed = 200;
            this.txbTimMaKH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbTimMaKH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbTimMaKH.BackColor = System.Drawing.Color.Transparent;
            this.txbTimMaKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbTimMaKH.BackgroundImage")));
            this.txbTimMaKH.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.txbTimMaKH.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbTimMaKH.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.txbTimMaKH.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbTimMaKH.BorderRadius = 1;
            this.txbTimMaKH.BorderThickness = 1;
            this.txbTimMaKH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbTimMaKH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTimMaKH.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.txbTimMaKH.DefaultText = "";
            this.txbTimMaKH.FillColor = System.Drawing.Color.White;
            this.txbTimMaKH.HideSelection = true;
            this.txbTimMaKH.IconLeft = null;
            this.txbTimMaKH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTimMaKH.IconPadding = 10;
            this.txbTimMaKH.IconRight = null;
            this.txbTimMaKH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTimMaKH.Lines = new string[0];
            this.txbTimMaKH.Location = new System.Drawing.Point(172, 32);
            this.txbTimMaKH.MaxLength = 32767;
            this.txbTimMaKH.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbTimMaKH.Modified = false;
            this.txbTimMaKH.Multiline = false;
            this.txbTimMaKH.Name = "txbTimMaKH";
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTimMaKH.OnActiveState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Empty;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbTimMaKH.OnDisabledState = stateProperties32;
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTimMaKH.OnHoverState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Silver;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Empty;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTimMaKH.OnIdleState = stateProperties34;
            this.txbTimMaKH.PasswordChar = '\0';
            this.txbTimMaKH.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbTimMaKH.PlaceholderText = "";
            this.txbTimMaKH.ReadOnly = false;
            this.txbTimMaKH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbTimMaKH.SelectedText = "";
            this.txbTimMaKH.SelectionLength = 0;
            this.txbTimMaKH.SelectionStart = 0;
            this.txbTimMaKH.ShortcutsEnabled = true;
            this.txbTimMaKH.Size = new System.Drawing.Size(253, 35);
            this.txbTimMaKH.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbTimMaKH.TabIndex = 23;
            this.txbTimMaKH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbTimMaKH.TextMarginBottom = 0;
            this.txbTimMaKH.TextMarginLeft = 5;
            this.txbTimMaKH.TextMarginTop = 0;
            this.txbTimMaKH.TextPlaceholder = "";
            this.txbTimMaKH.UseSystemPasswordChar = false;
            this.txbTimMaKH.WordWrap = true;
            // 
            // UC_KhachHang
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.bunifuPages1);
            this.Name = "UC_KhachHang";
            this.Size = new System.Drawing.Size(1151, 628);
            this.bunifuPages1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.grbChinhSuaMon.ResumeLayout(false);
            this.grbChinhSuaMon.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dtgvKH)).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPages bunifuPages1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.GroupBox groupBox3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTimKiem;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbTimMaKH;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuDataGridView dtgvKH;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnReload;
        private System.Windows.Forms.GroupBox grbChinhSuaMon;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHuyKH;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLuuKH;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbSuaTenKH;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbSuaSDT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSuaKH;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbSuaMaKH;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThemKH;
        private System.Windows.Forms.Label label9;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoaKH;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbTimTenKH;
    }
}
