namespace QuanLyKhachHang.UserControls
{
    partial class UC_KhuyenMai
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UC_KhuyenMai));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.dtgvKMList = new Bunifu.Framework.UI.BunifuCustomDataGrid();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.btnTimKiem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtSPhanTram = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtSMaKM = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btnHuyKM = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLuuKM = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtPhanTram = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnSuaKM = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtMaKM = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.btnThemKM = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label3 = new System.Windows.Forms.Label();
            this.btnXoaKM = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuTextBox3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.bunifuTextBox4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dtgvKMList)).BeginInit();
            this.groupBox3.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // dtgvKMList
            // 
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.dtgvKMList.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtgvKMList.BackgroundColor = System.Drawing.Color.Gainsboro;
            this.dtgvKMList.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtgvKMList.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.SeaGreen;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.SeaGreen;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtgvKMList.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtgvKMList.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dtgvKMList.DoubleBuffered = true;
            this.dtgvKMList.EnableHeadersVisualStyles = false;
            this.dtgvKMList.HeaderBgColor = System.Drawing.Color.SeaGreen;
            this.dtgvKMList.HeaderForeColor = System.Drawing.Color.SeaGreen;
            this.dtgvKMList.Location = new System.Drawing.Point(14, 152);
            this.dtgvKMList.Name = "dtgvKMList";
            this.dtgvKMList.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.dtgvKMList.Size = new System.Drawing.Size(673, 460);
            this.dtgvKMList.TabIndex = 0;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.btnTimKiem);
            this.groupBox3.Controls.Add(this.txtSPhanTram);
            this.groupBox3.Controls.Add(this.txtSMaKM);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.label8);
            this.groupBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.groupBox3.Location = new System.Drawing.Point(14, 7);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(1121, 128);
            this.groupBox3.TabIndex = 37;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Tìm kiếm";
            // 
            // btnTimKiem
            // 
            this.btnTimKiem.AllowToggling = false;
            this.btnTimKiem.AnimationSpeed = 200;
            this.btnTimKiem.AutoGenerateColors = true;
            this.btnTimKiem.BackColor = System.Drawing.Color.Transparent;
            this.btnTimKiem.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.btnTimKiem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTimKiem.BackgroundImage")));
            this.btnTimKiem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTimKiem.ButtonText = "Tìm Kiếm";
            this.btnTimKiem.ButtonTextMarginLeft = 0;
            this.btnTimKiem.ColorContrastOnClick = 45;
            this.btnTimKiem.ColorContrastOnHover = 45;
            this.btnTimKiem.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnTimKiem.CustomizableEdges = borderEdges1;
            this.btnTimKiem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTimKiem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTimKiem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTimKiem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTimKiem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTimKiem.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.btnTimKiem.ForeColor = System.Drawing.Color.White;
            this.btnTimKiem.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTimKiem.IconMarginLeft = 11;
            this.btnTimKiem.IconPadding = 10;
            this.btnTimKiem.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTimKiem.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.btnTimKiem.IdleBorderRadius = 5;
            this.btnTimKiem.IdleBorderThickness = 1;
            this.btnTimKiem.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.btnTimKiem.IdleIconLeftImage = null;
            this.btnTimKiem.IdleIconRightImage = null;
            this.btnTimKiem.IndicateFocus = false;
            this.btnTimKiem.Location = new System.Drawing.Point(952, 42);
            this.btnTimKiem.Name = "btnTimKiem";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(211)))), ((int)(((byte)(175)))));
            stateProperties1.BorderRadius = 5;
            stateProperties1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties1.BorderThickness = 1;
            stateProperties1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(211)))), ((int)(((byte)(175)))));
            stateProperties1.ForeColor = System.Drawing.Color.White;
            stateProperties1.IconLeftImage = null;
            stateProperties1.IconRightImage = null;
            this.btnTimKiem.onHoverState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(96)))), ((int)(((byte)(61)))));
            stateProperties2.BorderRadius = 5;
            stateProperties2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties2.BorderThickness = 1;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(96)))), ((int)(((byte)(61)))));
            stateProperties2.ForeColor = System.Drawing.Color.White;
            stateProperties2.IconLeftImage = null;
            stateProperties2.IconRightImage = null;
            this.btnTimKiem.OnPressedState = stateProperties2;
            this.btnTimKiem.Size = new System.Drawing.Size(118, 35);
            this.btnTimKiem.TabIndex = 27;
            this.btnTimKiem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTimKiem.TextMarginLeft = 0;
            this.btnTimKiem.UseDefaultRadiusAndThickness = true;
            // 
            // txtSPhanTram
            // 
            this.txtSPhanTram.AcceptsReturn = false;
            this.txtSPhanTram.AcceptsTab = false;
            this.txtSPhanTram.AnimationSpeed = 200;
            this.txtSPhanTram.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSPhanTram.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSPhanTram.BackColor = System.Drawing.Color.Transparent;
            this.txtSPhanTram.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSPhanTram.BackgroundImage")));
            this.txtSPhanTram.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.txtSPhanTram.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtSPhanTram.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.txtSPhanTram.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSPhanTram.BorderRadius = 1;
            this.txtSPhanTram.BorderThickness = 1;
            this.txtSPhanTram.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSPhanTram.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSPhanTram.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.txtSPhanTram.DefaultText = "";
            this.txtSPhanTram.FillColor = System.Drawing.Color.White;
            this.txtSPhanTram.HideSelection = true;
            this.txtSPhanTram.IconLeft = null;
            this.txtSPhanTram.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSPhanTram.IconPadding = 10;
            this.txtSPhanTram.IconRight = null;
            this.txtSPhanTram.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSPhanTram.Lines = new string[0];
            this.txtSPhanTram.Location = new System.Drawing.Point(648, 42);
            this.txtSPhanTram.MaxLength = 32767;
            this.txtSPhanTram.MinimumSize = new System.Drawing.Size(100, 35);
            this.txtSPhanTram.Modified = false;
            this.txtSPhanTram.Multiline = false;
            this.txtSPhanTram.Name = "txtSPhanTram";
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSPhanTram.OnActiveState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Empty;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSPhanTram.OnDisabledState = stateProperties4;
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSPhanTram.OnHoverState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Silver;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSPhanTram.OnIdleState = stateProperties6;
            this.txtSPhanTram.PasswordChar = '\0';
            this.txtSPhanTram.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSPhanTram.PlaceholderText = "";
            this.txtSPhanTram.ReadOnly = false;
            this.txtSPhanTram.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSPhanTram.SelectedText = "";
            this.txtSPhanTram.SelectionLength = 0;
            this.txtSPhanTram.SelectionStart = 0;
            this.txtSPhanTram.ShortcutsEnabled = true;
            this.txtSPhanTram.Size = new System.Drawing.Size(253, 35);
            this.txtSPhanTram.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtSPhanTram.TabIndex = 23;
            this.txtSPhanTram.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSPhanTram.TextMarginBottom = 0;
            this.txtSPhanTram.TextMarginLeft = 5;
            this.txtSPhanTram.TextMarginTop = 0;
            this.txtSPhanTram.TextPlaceholder = "";
            this.txtSPhanTram.UseSystemPasswordChar = false;
            this.txtSPhanTram.WordWrap = true;
            this.txtSPhanTram.TextChanged += new System.EventHandler(this.txtSPhanTram_TextChanged);
            // 
            // txtSMaKM
            // 
            this.txtSMaKM.AcceptsReturn = false;
            this.txtSMaKM.AcceptsTab = false;
            this.txtSMaKM.AnimationSpeed = 200;
            this.txtSMaKM.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSMaKM.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSMaKM.BackColor = System.Drawing.Color.Transparent;
            this.txtSMaKM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSMaKM.BackgroundImage")));
            this.txtSMaKM.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.txtSMaKM.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtSMaKM.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.txtSMaKM.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSMaKM.BorderRadius = 1;
            this.txtSMaKM.BorderThickness = 1;
            this.txtSMaKM.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSMaKM.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSMaKM.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.txtSMaKM.DefaultText = "";
            this.txtSMaKM.FillColor = System.Drawing.Color.White;
            this.txtSMaKM.HideSelection = true;
            this.txtSMaKM.IconLeft = null;
            this.txtSMaKM.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSMaKM.IconPadding = 10;
            this.txtSMaKM.IconRight = null;
            this.txtSMaKM.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSMaKM.Lines = new string[0];
            this.txtSMaKM.Location = new System.Drawing.Point(185, 42);
            this.txtSMaKM.MaxLength = 32767;
            this.txtSMaKM.MinimumSize = new System.Drawing.Size(100, 35);
            this.txtSMaKM.Modified = false;
            this.txtSMaKM.Multiline = false;
            this.txtSMaKM.Name = "txtSMaKM";
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSMaKM.OnActiveState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Empty;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSMaKM.OnDisabledState = stateProperties8;
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSMaKM.OnHoverState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Silver;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSMaKM.OnIdleState = stateProperties10;
            this.txtSMaKM.PasswordChar = '\0';
            this.txtSMaKM.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSMaKM.PlaceholderText = "";
            this.txtSMaKM.ReadOnly = false;
            this.txtSMaKM.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSMaKM.SelectedText = "";
            this.txtSMaKM.SelectionLength = 0;
            this.txtSMaKM.SelectionStart = 0;
            this.txtSMaKM.ShortcutsEnabled = true;
            this.txtSMaKM.Size = new System.Drawing.Size(253, 35);
            this.txtSMaKM.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtSMaKM.TabIndex = 22;
            this.txtSMaKM.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSMaKM.TextMarginBottom = 0;
            this.txtSMaKM.TextMarginLeft = 5;
            this.txtSMaKM.TextMarginTop = 0;
            this.txtSMaKM.TextPlaceholder = "";
            this.txtSMaKM.UseSystemPasswordChar = false;
            this.txtSMaKM.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label7.Location = new System.Drawing.Point(472, 57);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(152, 20);
            this.label7.TabIndex = 20;
            this.label7.Text = "Tên nhà cung cấp";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label8.Location = new System.Drawing.Point(6, 57);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(146, 20);
            this.label8.TabIndex = 21;
            this.label8.Text = "Mã nhà cung cấp";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.bunifuTextBox4);
            this.groupBox1.Controls.Add(this.bunifuTextBox3);
            this.groupBox1.Controls.Add(this.btnHuyKM);
            this.groupBox1.Controls.Add(this.btnLuuKM);
            this.groupBox1.Controls.Add(this.txtPhanTram);
            this.groupBox1.Controls.Add(this.btnSuaKM);
            this.groupBox1.Controls.Add(this.txtMaKM);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.btnThemKM);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.btnXoaKM);
            this.groupBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.groupBox1.Location = new System.Drawing.Point(709, 144);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(426, 468);
            this.groupBox1.TabIndex = 42;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Chỉnh sửa";
            // 
            // btnHuyKM
            // 
            this.btnHuyKM.AllowToggling = false;
            this.btnHuyKM.AnimationSpeed = 200;
            this.btnHuyKM.AutoGenerateColors = true;
            this.btnHuyKM.BackColor = System.Drawing.Color.Transparent;
            this.btnHuyKM.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.btnHuyKM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHuyKM.BackgroundImage")));
            this.btnHuyKM.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuyKM.ButtonText = "Hủy";
            this.btnHuyKM.ButtonTextMarginLeft = 0;
            this.btnHuyKM.ColorContrastOnClick = 45;
            this.btnHuyKM.ColorContrastOnHover = 45;
            this.btnHuyKM.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnHuyKM.CustomizableEdges = borderEdges2;
            this.btnHuyKM.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHuyKM.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHuyKM.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHuyKM.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHuyKM.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHuyKM.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.btnHuyKM.ForeColor = System.Drawing.Color.White;
            this.btnHuyKM.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHuyKM.IconMarginLeft = 11;
            this.btnHuyKM.IconPadding = 10;
            this.btnHuyKM.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHuyKM.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.btnHuyKM.IdleBorderRadius = 5;
            this.btnHuyKM.IdleBorderThickness = 1;
            this.btnHuyKM.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.btnHuyKM.IdleIconLeftImage = null;
            this.btnHuyKM.IdleIconRightImage = null;
            this.btnHuyKM.IndicateFocus = false;
            this.btnHuyKM.Location = new System.Drawing.Point(246, 353);
            this.btnHuyKM.Name = "btnHuyKM";
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(134)))), ((int)(((byte)(147)))));
            stateProperties19.BorderRadius = 5;
            stateProperties19.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties19.BorderThickness = 1;
            stateProperties19.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(134)))), ((int)(((byte)(147)))));
            stateProperties19.ForeColor = System.Drawing.Color.White;
            stateProperties19.IconLeftImage = null;
            stateProperties19.IconRightImage = null;
            this.btnHuyKM.onHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(19)))), ((int)(((byte)(33)))));
            stateProperties20.BorderRadius = 5;
            stateProperties20.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties20.BorderThickness = 1;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(19)))), ((int)(((byte)(33)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.IconLeftImage = null;
            stateProperties20.IconRightImage = null;
            this.btnHuyKM.OnPressedState = stateProperties20;
            this.btnHuyKM.Size = new System.Drawing.Size(118, 45);
            this.btnHuyKM.TabIndex = 28;
            this.btnHuyKM.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHuyKM.TextMarginLeft = 0;
            this.btnHuyKM.UseDefaultRadiusAndThickness = true;
            this.btnHuyKM.Click += new System.EventHandler(this.btnHuyKM_Click_1);
            // 
            // btnLuuKM
            // 
            this.btnLuuKM.AllowToggling = false;
            this.btnLuuKM.AnimationSpeed = 200;
            this.btnLuuKM.AutoGenerateColors = true;
            this.btnLuuKM.BackColor = System.Drawing.Color.Transparent;
            this.btnLuuKM.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.btnLuuKM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLuuKM.BackgroundImage")));
            this.btnLuuKM.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuuKM.ButtonText = "Lưu";
            this.btnLuuKM.ButtonTextMarginLeft = 0;
            this.btnLuuKM.ColorContrastOnClick = 45;
            this.btnLuuKM.ColorContrastOnHover = 45;
            this.btnLuuKM.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnLuuKM.CustomizableEdges = borderEdges3;
            this.btnLuuKM.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLuuKM.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLuuKM.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLuuKM.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLuuKM.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLuuKM.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.btnLuuKM.ForeColor = System.Drawing.Color.White;
            this.btnLuuKM.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLuuKM.IconMarginLeft = 11;
            this.btnLuuKM.IconPadding = 10;
            this.btnLuuKM.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLuuKM.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.btnLuuKM.IdleBorderRadius = 5;
            this.btnLuuKM.IdleBorderThickness = 1;
            this.btnLuuKM.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.btnLuuKM.IdleIconLeftImage = null;
            this.btnLuuKM.IdleIconRightImage = null;
            this.btnLuuKM.IndicateFocus = false;
            this.btnLuuKM.Location = new System.Drawing.Point(111, 353);
            this.btnLuuKM.Name = "btnLuuKM";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(152)))), ((int)(((byte)(181)))));
            stateProperties21.BorderRadius = 5;
            stateProperties21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties21.BorderThickness = 1;
            stateProperties21.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(152)))), ((int)(((byte)(181)))));
            stateProperties21.ForeColor = System.Drawing.Color.White;
            stateProperties21.IconLeftImage = null;
            stateProperties21.IconRightImage = null;
            this.btnLuuKM.onHoverState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(37)))), ((int)(((byte)(67)))));
            stateProperties22.BorderRadius = 5;
            stateProperties22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties22.BorderThickness = 1;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(37)))), ((int)(((byte)(67)))));
            stateProperties22.ForeColor = System.Drawing.Color.White;
            stateProperties22.IconLeftImage = null;
            stateProperties22.IconRightImage = null;
            this.btnLuuKM.OnPressedState = stateProperties22;
            this.btnLuuKM.Size = new System.Drawing.Size(117, 45);
            this.btnLuuKM.TabIndex = 29;
            this.btnLuuKM.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLuuKM.TextMarginLeft = 0;
            this.btnLuuKM.UseDefaultRadiusAndThickness = true;
            // 
            // txtPhanTram
            // 
            this.txtPhanTram.AcceptsReturn = false;
            this.txtPhanTram.AcceptsTab = false;
            this.txtPhanTram.AnimationSpeed = 200;
            this.txtPhanTram.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhanTram.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhanTram.BackColor = System.Drawing.Color.Transparent;
            this.txtPhanTram.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhanTram.BackgroundImage")));
            this.txtPhanTram.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.txtPhanTram.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtPhanTram.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.txtPhanTram.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPhanTram.BorderRadius = 1;
            this.txtPhanTram.BorderThickness = 1;
            this.txtPhanTram.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhanTram.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhanTram.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.txtPhanTram.DefaultText = "";
            this.txtPhanTram.FillColor = System.Drawing.Color.White;
            this.txtPhanTram.HideSelection = true;
            this.txtPhanTram.IconLeft = null;
            this.txtPhanTram.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhanTram.IconPadding = 10;
            this.txtPhanTram.IconRight = null;
            this.txtPhanTram.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhanTram.Lines = new string[0];
            this.txtPhanTram.Location = new System.Drawing.Point(161, 215);
            this.txtPhanTram.MaxLength = 32767;
            this.txtPhanTram.MinimumSize = new System.Drawing.Size(100, 35);
            this.txtPhanTram.Modified = false;
            this.txtPhanTram.Multiline = false;
            this.txtPhanTram.Name = "txtPhanTram";
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhanTram.OnActiveState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Empty;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhanTram.OnDisabledState = stateProperties24;
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhanTram.OnHoverState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Silver;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhanTram.OnIdleState = stateProperties26;
            this.txtPhanTram.PasswordChar = '\0';
            this.txtPhanTram.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhanTram.PlaceholderText = "";
            this.txtPhanTram.ReadOnly = false;
            this.txtPhanTram.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhanTram.SelectedText = "";
            this.txtPhanTram.SelectionLength = 0;
            this.txtPhanTram.SelectionStart = 0;
            this.txtPhanTram.ShortcutsEnabled = true;
            this.txtPhanTram.Size = new System.Drawing.Size(259, 35);
            this.txtPhanTram.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtPhanTram.TabIndex = 22;
            this.txtPhanTram.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhanTram.TextMarginBottom = 0;
            this.txtPhanTram.TextMarginLeft = 5;
            this.txtPhanTram.TextMarginTop = 0;
            this.txtPhanTram.TextPlaceholder = "";
            this.txtPhanTram.UseSystemPasswordChar = false;
            this.txtPhanTram.WordWrap = true;
            // 
            // btnSuaKM
            // 
            this.btnSuaKM.AllowToggling = false;
            this.btnSuaKM.AnimationSpeed = 200;
            this.btnSuaKM.AutoGenerateColors = true;
            this.btnSuaKM.BackColor = System.Drawing.Color.Transparent;
            this.btnSuaKM.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSuaKM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSuaKM.BackgroundImage")));
            this.btnSuaKM.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSuaKM.ButtonText = "Sửa";
            this.btnSuaKM.ButtonTextMarginLeft = 0;
            this.btnSuaKM.ColorContrastOnClick = 45;
            this.btnSuaKM.ColorContrastOnHover = 45;
            this.btnSuaKM.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnSuaKM.CustomizableEdges = borderEdges4;
            this.btnSuaKM.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSuaKM.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSuaKM.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuaKM.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuaKM.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSuaKM.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.btnSuaKM.ForeColor = System.Drawing.Color.White;
            this.btnSuaKM.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSuaKM.IconMarginLeft = 11;
            this.btnSuaKM.IconPadding = 10;
            this.btnSuaKM.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSuaKM.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSuaKM.IdleBorderRadius = 5;
            this.btnSuaKM.IdleBorderThickness = 1;
            this.btnSuaKM.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnSuaKM.IdleIconLeftImage = null;
            this.btnSuaKM.IdleIconRightImage = null;
            this.btnSuaKM.IndicateFocus = false;
            this.btnSuaKM.Location = new System.Drawing.Point(174, 284);
            this.btnSuaKM.Name = "btnSuaKM";
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(185)))), ((int)(((byte)(114)))));
            stateProperties27.BorderRadius = 5;
            stateProperties27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties27.BorderThickness = 1;
            stateProperties27.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(185)))), ((int)(((byte)(114)))));
            stateProperties27.ForeColor = System.Drawing.Color.White;
            stateProperties27.IconLeftImage = null;
            stateProperties27.IconRightImage = null;
            this.btnSuaKM.onHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(70)))), ((int)(((byte)(0)))));
            stateProperties28.BorderRadius = 5;
            stateProperties28.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties28.BorderThickness = 1;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(70)))), ((int)(((byte)(0)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.IconLeftImage = null;
            stateProperties28.IconRightImage = null;
            this.btnSuaKM.OnPressedState = stateProperties28;
            this.btnSuaKM.Size = new System.Drawing.Size(115, 45);
            this.btnSuaKM.TabIndex = 23;
            this.btnSuaKM.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSuaKM.TextMarginLeft = 0;
            this.btnSuaKM.UseDefaultRadiusAndThickness = true;
            // 
            // txtMaKM
            // 
            this.txtMaKM.AcceptsReturn = false;
            this.txtMaKM.AcceptsTab = false;
            this.txtMaKM.AnimationSpeed = 200;
            this.txtMaKM.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMaKM.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMaKM.BackColor = System.Drawing.Color.Transparent;
            this.txtMaKM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMaKM.BackgroundImage")));
            this.txtMaKM.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.txtMaKM.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtMaKM.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.txtMaKM.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMaKM.BorderRadius = 1;
            this.txtMaKM.BorderThickness = 1;
            this.txtMaKM.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaKM.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaKM.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.txtMaKM.DefaultText = "";
            this.txtMaKM.FillColor = System.Drawing.Color.White;
            this.txtMaKM.HideSelection = true;
            this.txtMaKM.IconLeft = null;
            this.txtMaKM.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaKM.IconPadding = 10;
            this.txtMaKM.IconRight = null;
            this.txtMaKM.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaKM.Lines = new string[0];
            this.txtMaKM.Location = new System.Drawing.Point(161, 41);
            this.txtMaKM.MaxLength = 32767;
            this.txtMaKM.MinimumSize = new System.Drawing.Size(100, 35);
            this.txtMaKM.Modified = false;
            this.txtMaKM.Multiline = false;
            this.txtMaKM.Name = "txtMaKM";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaKM.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Empty;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Empty;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaKM.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaKM.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaKM.OnIdleState = stateProperties32;
            this.txtMaKM.PasswordChar = '\0';
            this.txtMaKM.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaKM.PlaceholderText = "";
            this.txtMaKM.ReadOnly = false;
            this.txtMaKM.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMaKM.SelectedText = "";
            this.txtMaKM.SelectionLength = 0;
            this.txtMaKM.SelectionStart = 0;
            this.txtMaKM.ShortcutsEnabled = true;
            this.txtMaKM.Size = new System.Drawing.Size(259, 35);
            this.txtMaKM.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtMaKM.TabIndex = 22;
            this.txtMaKM.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaKM.TextMarginBottom = 0;
            this.txtMaKM.TextMarginLeft = 5;
            this.txtMaKM.TextMarginTop = 0;
            this.txtMaKM.TextPlaceholder = "";
            this.txtMaKM.UseSystemPasswordChar = false;
            this.txtMaKM.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label6.Location = new System.Drawing.Point(17, 230);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(64, 20);
            this.label6.TabIndex = 21;
            this.label6.Text = "Địa chỉ";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label1.Location = new System.Drawing.Point(6, 118);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(152, 20);
            this.label1.TabIndex = 20;
            this.label1.Text = "Tên nhà cung cấp";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label2.Location = new System.Drawing.Point(6, 171);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(115, 20);
            this.label2.TabIndex = 21;
            this.label2.Text = "Số điện thoại";
            // 
            // btnThemKM
            // 
            this.btnThemKM.AllowToggling = false;
            this.btnThemKM.AnimationSpeed = 200;
            this.btnThemKM.AutoGenerateColors = true;
            this.btnThemKM.BackColor = System.Drawing.Color.Transparent;
            this.btnThemKM.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnThemKM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThemKM.BackgroundImage")));
            this.btnThemKM.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemKM.ButtonText = "Thêm";
            this.btnThemKM.ButtonTextMarginLeft = 0;
            this.btnThemKM.ColorContrastOnClick = 45;
            this.btnThemKM.ColorContrastOnHover = 45;
            this.btnThemKM.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnThemKM.CustomizableEdges = borderEdges5;
            this.btnThemKM.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThemKM.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThemKM.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThemKM.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThemKM.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThemKM.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.btnThemKM.ForeColor = System.Drawing.Color.White;
            this.btnThemKM.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThemKM.IconMarginLeft = 11;
            this.btnThemKM.IconPadding = 10;
            this.btnThemKM.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThemKM.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnThemKM.IdleBorderRadius = 5;
            this.btnThemKM.IdleBorderThickness = 1;
            this.btnThemKM.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnThemKM.IdleIconLeftImage = null;
            this.btnThemKM.IdleIconRightImage = null;
            this.btnThemKM.IndicateFocus = false;
            this.btnThemKM.Location = new System.Drawing.Point(41, 284);
            this.btnThemKM.Name = "btnThemKM";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties33.BorderRadius = 5;
            stateProperties33.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties33.BorderThickness = 1;
            stateProperties33.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties33.ForeColor = System.Drawing.Color.White;
            stateProperties33.IconLeftImage = null;
            stateProperties33.IconRightImage = null;
            this.btnThemKM.onHoverState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties34.BorderRadius = 5;
            stateProperties34.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties34.BorderThickness = 1;
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties34.ForeColor = System.Drawing.Color.White;
            stateProperties34.IconLeftImage = null;
            stateProperties34.IconRightImage = null;
            this.btnThemKM.OnPressedState = stateProperties34;
            this.btnThemKM.Size = new System.Drawing.Size(117, 45);
            this.btnThemKM.TabIndex = 24;
            this.btnThemKM.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThemKM.TextMarginLeft = 0;
            this.btnThemKM.UseDefaultRadiusAndThickness = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(176)))), ((int)(((byte)(111)))));
            this.label3.Location = new System.Drawing.Point(6, 56);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(146, 20);
            this.label3.TabIndex = 21;
            this.label3.Text = "Mã nhà cung cấp";
            // 
            // btnXoaKM
            // 
            this.btnXoaKM.AllowToggling = false;
            this.btnXoaKM.AnimationSpeed = 200;
            this.btnXoaKM.AutoGenerateColors = true;
            this.btnXoaKM.BackColor = System.Drawing.Color.Transparent;
            this.btnXoaKM.BackColor1 = System.Drawing.Color.Red;
            this.btnXoaKM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoaKM.BackgroundImage")));
            this.btnXoaKM.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaKM.ButtonText = "Xoá";
            this.btnXoaKM.ButtonTextMarginLeft = 0;
            this.btnXoaKM.ColorContrastOnClick = 45;
            this.btnXoaKM.ColorContrastOnHover = 45;
            this.btnXoaKM.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnXoaKM.CustomizableEdges = borderEdges6;
            this.btnXoaKM.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoaKM.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnXoaKM.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoaKM.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoaKM.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoaKM.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.btnXoaKM.ForeColor = System.Drawing.Color.White;
            this.btnXoaKM.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXoaKM.IconMarginLeft = 11;
            this.btnXoaKM.IconPadding = 10;
            this.btnXoaKM.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXoaKM.IdleBorderColor = System.Drawing.Color.Red;
            this.btnXoaKM.IdleBorderRadius = 5;
            this.btnXoaKM.IdleBorderThickness = 1;
            this.btnXoaKM.IdleFillColor = System.Drawing.Color.Red;
            this.btnXoaKM.IdleIconLeftImage = null;
            this.btnXoaKM.IdleIconRightImage = null;
            this.btnXoaKM.IndicateFocus = false;
            this.btnXoaKM.Location = new System.Drawing.Point(302, 284);
            this.btnXoaKM.Name = "btnXoaKM";
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            stateProperties35.BorderRadius = 5;
            stateProperties35.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties35.BorderThickness = 1;
            stateProperties35.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            stateProperties35.ForeColor = System.Drawing.Color.White;
            stateProperties35.IconLeftImage = null;
            stateProperties35.IconRightImage = null;
            this.btnXoaKM.onHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            stateProperties36.BorderRadius = 5;
            stateProperties36.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties36.BorderThickness = 1;
            stateProperties36.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            stateProperties36.ForeColor = System.Drawing.Color.White;
            stateProperties36.IconLeftImage = null;
            stateProperties36.IconRightImage = null;
            this.btnXoaKM.OnPressedState = stateProperties36;
            this.btnXoaKM.Size = new System.Drawing.Size(118, 45);
            this.btnXoaKM.TabIndex = 22;
            this.btnXoaKM.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoaKM.TextMarginLeft = 0;
            this.btnXoaKM.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuTextBox3
            // 
            this.bunifuTextBox3.AcceptsReturn = false;
            this.bunifuTextBox3.AcceptsTab = false;
            this.bunifuTextBox3.AnimationSpeed = 200;
            this.bunifuTextBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox3.BackgroundImage")));
            this.bunifuTextBox3.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.bunifuTextBox3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.bunifuTextBox3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.bunifuTextBox3.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox3.BorderRadius = 1;
            this.bunifuTextBox3.BorderThickness = 1;
            this.bunifuTextBox3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox3.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.bunifuTextBox3.DefaultText = "";
            this.bunifuTextBox3.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox3.HideSelection = true;
            this.bunifuTextBox3.IconLeft = null;
            this.bunifuTextBox3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.IconPadding = 10;
            this.bunifuTextBox3.IconRight = null;
            this.bunifuTextBox3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.Lines = new string[0];
            this.bunifuTextBox3.Location = new System.Drawing.Point(161, 101);
            this.bunifuTextBox3.MaxLength = 32767;
            this.bunifuTextBox3.MinimumSize = new System.Drawing.Size(100, 35);
            this.bunifuTextBox3.Modified = false;
            this.bunifuTextBox3.Multiline = false;
            this.bunifuTextBox3.Name = "bunifuTextBox3";
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnActiveState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Empty;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox3.OnDisabledState = stateProperties16;
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnHoverState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Silver;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnIdleState = stateProperties18;
            this.bunifuTextBox3.PasswordChar = '\0';
            this.bunifuTextBox3.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox3.PlaceholderText = "";
            this.bunifuTextBox3.ReadOnly = false;
            this.bunifuTextBox3.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox3.SelectedText = "";
            this.bunifuTextBox3.SelectionLength = 0;
            this.bunifuTextBox3.SelectionStart = 0;
            this.bunifuTextBox3.ShortcutsEnabled = true;
            this.bunifuTextBox3.Size = new System.Drawing.Size(259, 37);
            this.bunifuTextBox3.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox3.TabIndex = 30;
            this.bunifuTextBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox3.TextMarginBottom = 0;
            this.bunifuTextBox3.TextMarginLeft = 5;
            this.bunifuTextBox3.TextMarginTop = 0;
            this.bunifuTextBox3.TextPlaceholder = "";
            this.bunifuTextBox3.UseSystemPasswordChar = false;
            this.bunifuTextBox3.WordWrap = true;
            // 
            // bunifuTextBox4
            // 
            this.bunifuTextBox4.AcceptsReturn = false;
            this.bunifuTextBox4.AcceptsTab = false;
            this.bunifuTextBox4.AnimationSpeed = 200;
            this.bunifuTextBox4.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox4.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox4.BackgroundImage")));
            this.bunifuTextBox4.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            this.bunifuTextBox4.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.bunifuTextBox4.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            this.bunifuTextBox4.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox4.BorderRadius = 1;
            this.bunifuTextBox4.BorderThickness = 1;
            this.bunifuTextBox4.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox4.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox4.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 11.25F);
            this.bunifuTextBox4.DefaultText = "";
            this.bunifuTextBox4.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox4.HideSelection = true;
            this.bunifuTextBox4.IconLeft = null;
            this.bunifuTextBox4.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox4.IconPadding = 10;
            this.bunifuTextBox4.IconRight = null;
            this.bunifuTextBox4.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox4.Lines = new string[0];
            this.bunifuTextBox4.Location = new System.Drawing.Point(161, 156);
            this.bunifuTextBox4.MaxLength = 32767;
            this.bunifuTextBox4.MinimumSize = new System.Drawing.Size(100, 35);
            this.bunifuTextBox4.Modified = false;
            this.bunifuTextBox4.Multiline = false;
            this.bunifuTextBox4.Name = "bunifuTextBox4";
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(56)))), ((int)(((byte)(107)))), ((int)(((byte)(140)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox4.OnActiveState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Empty;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox4.OnDisabledState = stateProperties12;
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(161)))), ((int)(((byte)(210)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox4.OnHoverState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Silver;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox4.OnIdleState = stateProperties14;
            this.bunifuTextBox4.PasswordChar = '\0';
            this.bunifuTextBox4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox4.PlaceholderText = "";
            this.bunifuTextBox4.ReadOnly = false;
            this.bunifuTextBox4.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox4.SelectedText = "";
            this.bunifuTextBox4.SelectionLength = 0;
            this.bunifuTextBox4.SelectionStart = 0;
            this.bunifuTextBox4.ShortcutsEnabled = true;
            this.bunifuTextBox4.Size = new System.Drawing.Size(259, 35);
            this.bunifuTextBox4.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox4.TabIndex = 31;
            this.bunifuTextBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox4.TextMarginBottom = 0;
            this.bunifuTextBox4.TextMarginLeft = 5;
            this.bunifuTextBox4.TextMarginTop = 0;
            this.bunifuTextBox4.TextPlaceholder = "";
            this.bunifuTextBox4.UseSystemPasswordChar = false;
            this.bunifuTextBox4.WordWrap = true;
            // 
            // UC_KhuyenMai
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.dtgvKMList);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "UC_KhuyenMai";
            this.Size = new System.Drawing.Size(1151, 628);
            ((System.ComponentModel.ISupportInitialize)(this.dtgvKMList)).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuCustomDataGrid dtgvKMList;
        private System.Windows.Forms.GroupBox groupBox3;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtSPhanTram;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtSMaKM;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.GroupBox groupBox1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtPhanTram;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSuaKM;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtMaKM;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThemKM;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoaKM;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHuyKM;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLuuKM;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTimKiem;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBox4;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBox3;
    }
}
